<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Demo.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SmolVm.Fable.fsproj" />
  </ItemGroup>
</Project>
